### ISSUE TITLE
Need?

### ISSUE THREAD

**Issue by wsjackson14** [uno-18wi-cist2100-004-group4/tu-tutor#17]
I really like your idea for schools that may not have a lot of tutors, but what about the schools that do have tutors readily available, many times for free? How would you compete with these types of schools, or would your service just not be of great use on those campuses?

**Comment by daairola** [comment]
Also, I can imagine that in some universities or in some subjects, you could find yourself lacking tutors. How would you plan ahead for a possible lack of tutors on some campuses?

**Comment by Kpalmquist** [comment]
Definitely with most universities offering tutors (free,) how are you going to combat between offering a tutoring service with a small fee in comparison to free tutors for campus students?

**Comment by davidlentsch** [comment]
Our service creates additional opportunities for students who want a more personal (and potentially more impactful) experience. Student's can access a tutor from anywhere, as tutors may not always be easily accessible or may already be completely scheduled. Larger universities would likely benefit from this service more than smaller universities as they have more students that they need to serve. However, smaller universities may be small enough that they don't have the tutoring services to offer to their students.
