### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by mattross1** [uno-18wi-cist2100-004-group4/tu-tutor#18]
Truly a standout concept for a business. While online tutors are very much a thing what your service does is make it a more accessible thing for the students and the tutors. Great idea, some universities have free tutoring services but definitely in a limited range of subjects, this definitely opens the doors for a lot more. Services like chegg do provide this wide range, but they emphasize on materials and less person to person. When expanding your business emphasis on being a service that connects people rather than a provider may suit you well.

**Comment by davidlentsch** [comment]
Thanks for your feedback!
