### ISSUE TITLE
Customer Segments and README

### ISSUE THREAD

**Issue by jdboyd-github** [uno-18wi-cist2100-004-group4/tu-tutor#25]
Something small may be just more description in your README file, and links to other areas on your page for ease of access.

Also your Customer Segment is very broad. It seems you mainly focus towards students, but you say "18 and older". I feel going deeper and finding different main audiences for this product would help its success.

**Comment by davidlentsch** [comment]
We will clarify the demographic for online students in particular, as they may get the most use out of this application.
