### ISSUE TITLE
Credibility of Tutors

### ISSUE THREAD

**Issue by MarcusABenesch** [uno-18wi-cist2100-004-group4/tu-tutor#26]
How do you determine that the tutors are credible in the field that they are tutoring? Perhaps require tutors to submit a transcript.

**Comment by rpruch** [comment]
Hi please see the Tutor Eligibility section of [T2](https://github.com/uno-18wi-cist2100-004-group4/tu-tutor/blob/master/T1.md). We mention transcripts there!
